version: '2'

services:
  postgres:
    restart: always
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5452:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASS: hackme
      POSTGRES_DB: url_shortener
